"""§5.5 Architect — Task.type design: produce docs/interface.md (no shipping code)."""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from orchestrator.types import ToolResult
from tools.filesystem import write_file
from xr_ai_co.context import assemble_messages
from xr_ai_co.llm import LLMProvider, LLMProviderError

log = logging.getLogger(__name__)

INTERFACE_PATH = "docs/interface.md"


def _extract_md_file(text: str) -> tuple[str, str] | None:
    pattern = r"```(?:markdown|md)?\s*:([^\n]+)\n(.*?)```"
    m = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    m2 = re.search(r"```(?:markdown|md)?\n(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if m2:
        return INTERFACE_PATH, m2.group(1).strip()
    return None


def design_stub(task: dict[str, Any], workspace: Path) -> ToolResult:
    """Deterministic interface sketch from TaskSpec."""
    title = task.get("description", "Component")[:200]
    body = (
        f"# Interface — {task.get('id')}\n\n"
        f"## Goal\n{title}\n\n"
        "## Public API\n"
        "- (Define public functions/classes and signatures here.)\n\n"
        "## Data model\n"
        "- (Entities, invariants, persistence notes.)\n\n"
        "## Dependencies\n"
        "- (External systems, libraries.)\n\n"
        "_Generated by architect stub — refine in design tasks._\n"
    )
    write_file(workspace, INTERFACE_PATH, body)
    return ToolResult(
        success=True,
        payload={"path": INTERFACE_PATH, "role": "architect"},
    )


def design_with_llm(
    task: dict[str, Any],
    session: dict[str, Any],
    workspace: Path,
    llm: LLMProvider,
    mission: str = "",
) -> ToolResult:
    """LLM produces Markdown interface spec under docs/interface.md."""
    sys_p, messages = assemble_messages(
        role="architect",
        task=task,
        session=session,
        mission=mission,
        workspace=workspace,
    )
    messages[0]["content"] += (
        f"\n\n**Instruction:** Write `docs/interface.md` (Markdown). "
        "Use a fenced block ```markdown:docs/interface.md ... ``` "
        "or ```markdown ... ```. Include: overview, public API, data model, non-goals."
    )
    try:
        resp = llm.chat(system=sys_p, messages=messages, max_tokens=4096, temperature=0.25)
    except LLMProviderError as e:
        log.error("architect LLM failed: %s", e)
        return ToolResult(success=False, error=f"llm_error: {e}", payload={"fallback": "stub"})

    extracted = _extract_md_file(resp.text)
    if extracted:
        rel, content = extracted
        if not rel.endswith(".md"):
            rel = INTERFACE_PATH
        write_file(workspace, rel, content)
    else:
        write_file(workspace, INTERFACE_PATH, resp.text.strip()[:24000])

    return ToolResult(
        success=True,
        payload={
            "path": INTERFACE_PATH,
            "role": "architect",
            "usage": {
                "prompt_tokens": resp.usage.prompt_tokens,
                "completion_tokens": resp.usage.completion_tokens,
            },
        },
    )
